### ISSUE TITLE
loadSlot breakpoints parameter does not appear to affect ad serving

### ISSUE THREAD

**Issue by sjferwerda** [depersgroep/dfp-web-advertising#4]
Thanks for the work that you've put into this repo. I've been testing out your code today and I'm not able to prevent ads from serving using the loadSlot breakpoints parameter as indicated in your documentation. When I set 'medium': false or 'small': false, the ad still renders. The only way I'm able to prevent the ad from serving is to set the 'medium': , or 'small': sizes parameter to empty.

You can see my test page here where I'm trying to not render an ad for nav-below ad slot on tablet (medium) or mobile (small).

https://www.greeleytribune.com/dfp-test/dfp-web-advertising-sandbox/

**Comment by sencro** [comment]
Hi sjferwerda,

Thanks for your input. 
The easiest solution would be leaving the size arrays empty for the medium and small breakpoints on the below-nav slot. 

```
'domId': 'below-nav',
      'sizes': {
          'large': [[728, 90]],
          'medium': [],
          'small': []
      }
```
This way the ad slots won't be defined at those breakpoints.

At this point we see some strange behavior in the DFP api. The script never calls the googletag.display function for your below-nav slot, which is ok. However it is being rendered. We will check if it's possible to not render defined ad slots

**Comment by sjferwerda** [comment]
Thanks for your quick reply.

I definitely cannot get https://github.com/depersgroep/dfp-web-advertising/blob/master/DOCUMENTATION.md#breakpoints-1 to work correctly as specified in your documentation. Passing false does not prevent the ad from displaying. Only setting a 'sizes' array value to empty [] as you've indicated, works.

Also, I noticed that in the DFP documentation it says:

> A browser size mapping of [0, 0] can be used to specify a default mapping that can be used on any browser size. To specify an ad that will fit any browser size, map an ad size to the [0, 0] browser size. 

https://support.google.com/admanager/answer/3423562?hl=en

That does not appear to work in your library. I've defined a breakpoint of 'default' as in:
`			'breakpoints': [
				{
					'name': 'default',
			 		'begin': 0,
			 		'end': 0
},...
]
`
and default does not trigger. I have to set 'end' to an actual value like 319 for 'default' to be recognized. Not sure if this 'default' spec is important to support??

Thanks!

**Comment by goowikns** [comment]
@sjferwerda 

Our approach for responsive advertisement is different. We don't actually use the sizeMapping, instead we change the adUnit structure (on script initialisation) and correspond them to the sizes array. 

Also for the breakpoint (per slot) to work, you need to have a corresponding empty array in the sizes when setting one of you breakpoint property of a slot to false. Like so:

```
// slot config
slots = [
	{
		'domId': 'leader--1',
		'sizes': {
			'large': new Array([[970, 250]]),
			'medium': new Array([]),
			'small': new Array([[300, 50]])
		},
		'targeting': {
			'pos': 'leader1'
		}
	}
];

//loadSlot
<div class="dfp" id="leader--1">
	<script>
		dfp.cmd.push(function() {
			dfp.loadSlot('leader--1', {
				'breakpoints': {
					'large': true,
					'medium': false, // false cause of empty array
					'small': true
				}
			})
		});
	</script>
</div>
```
