### ISSUE TITLE
Services configuration update in documentation

### ISSUE THREAD

**Issue by sjferwerda** [depersgroep/dfp-web-advertising#8]
Thanks for continuing to work on this library. It seems to be working pretty well in my ongoing testing. I had one slight issue with requestNonPersonalizedAds but I believe your recent commit (https://github.com/depersgroep/dfp-web-advertising/commit/472b027e4271df0a9aef4870e81d5d173c852aee) fixed that inconsistency. In addition, wrapping the configuration settings in 'services': {} also helped. It appears that you should update your README configuration section (https://github.com/depersgroep/dfp-web-advertising#configuration) and perhaps DOCUMENTATION.md to show the use of opts.services correctly. I changed:
<code><pre>'async': true,
    'singleRequest': true,
    'collapseEmpty': true,
    'disableInitialLoad': false,
    //'ppid': '12hjDojdj2JHK32228FHKJBskMOI2ndnjndn',
    'requestNonPersonalizedAds': 0,
    'breakpoints': [...],
    'callbacks': {...}
</pre></code>
to:
<pre><code>'services': {
    'async': true,
    'singleRequest': true,
    'collapseEmpty': true,
    'disableInitialLoad': false,
    //'ppid': '12hjDojdj2JHK32228FHKJBskMOI2ndnjndn',
    'requestNonPersonalizedAds': 0
},
'breakpoints': [...],
'callbacks': {...}
</code></pre>
and now my custom configuration settings appear to work.

Perhaps you could also add some information about your ?taginfo=console debug feature as well. 

Thanks again!

**Comment by goowikns** [comment]
@sjferwerda Thanks for bringing it up. The documentation has been updated
