### ISSUE TITLE
Ad slots rendering without loadSlot being called

### ISSUE THREAD

**Issue by sjferwerda** [depersgroep/dfp-web-advertising#9]
Not sure if this is a bug, but in one my latest tests (http://jsbin.com/dumahaz/1/edit?html,js,output) you can see that all six divs/slots are rendering even though the only slot that uses loadSlot is the very first "ad-top" slot. Here's the html:
```
<div id="ad-top" class="dfp">
<script>
	dfp.cmd.push(function() {
		dfp.loadSlot('ad-top', {
			'breakpoints': {
			    'xl': true,
			    'l': true,
			    'm': true,
			    's': true,
			    'xs': true
			    }
			 })
		 });
	</script>
</div>

<p>ad-bottom</p>
<div id="ad-bottom" class="dfp"></div>

<p>ad-big-box1</p>
<div id="ad-big-box1" class="dfp"></div>

<p>ad-big-box2</p>
<div id="ad-big-box2" class="dfp"></div>

<p>ad-big-box3</p>
<div id="ad-big-box3" class="dfp"></div>

<p>ad-half-page</p>
<div id="ad-half-page" class="dfp"></div>
```
I believe that tar.loadSlot and _lazyLoadSlot are the only two methods that call w.googletag.display(domId), so I'm not quite sure how these empty divs are rendering without an explicit call to loadSlot. I've got disableInitialLoad set to false which I assume would disable any kind of lazy loading or rendering via lazy loading methods.

**Comment by goowikns** [comment]
@sjferwerda Hey it seems we completely missed this issue.

All configured slots are indeed defined, whether you implement the corresponding loadslot or not. 

As a temporary working fix, you can use the **dfp.loadLazySlot(slot, options)**, these slots shouldn't be configured within the head but instead inline.
